# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CodeLibrary\pytemplate\src\pytemplate\gui\generate.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(631, 157)
        Form.setMinimumSize(QtCore.QSize(418, 120))
        Form.setMaximumSize(QtCore.QSize(99999, 99999))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_template = QtWidgets.QLineEdit(Form)
        self.lineEdit_template.setEnabled(True)
        self.lineEdit_template.setObjectName("lineEdit_template")
        self.gridLayout_4.addWidget(self.lineEdit_template, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 0, 1, 1)
        self.lineEdit_output = QtWidgets.QLineEdit(Form)
        self.lineEdit_output.setEnabled(True)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.gridLayout_4.addWidget(self.lineEdit_output, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 5, 1, 1, 1)
        self.toolButton_output = QtWidgets.QToolButton(Form)
        self.toolButton_output.setObjectName("toolButton_output")
        self.gridLayout_4.addWidget(self.toolButton_output, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_data = QtWidgets.QLineEdit(Form)
        self.lineEdit_data.setEnabled(True)
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.gridLayout_4.addWidget(self.lineEdit_data, 2, 1, 1, 1)
        self.toolButton_data = QtWidgets.QToolButton(Form)
        self.toolButton_data.setObjectName("toolButton_data")
        self.gridLayout_4.addWidget(self.toolButton_data, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.toolButton_template = QtWidgets.QToolButton(Form)
        self.toolButton_template.setObjectName("toolButton_template")
        self.gridLayout_4.addWidget(self.toolButton_template, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 2, -1, 5)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_generate = QtWidgets.QPushButton(Form)
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.horizontalLayout.addWidget(self.pushButton_generate)
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout.addWidget(self.pushButton_exit)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "批量模板合成工具"))
        self.label_3.setText(_translate("Form", "输出文件夹："))
        self.toolButton_output.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "数据文件路径："))
        self.toolButton_data.setText(_translate("Form", "..."))
        self.label.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("Form", "模板文件路径："))
        self.toolButton_template.setText(_translate("Form", "..."))
        self.pushButton_generate.setText(_translate("Form", "生成"))
        self.pushButton_exit.setText(_translate("Form", "退出"))
